# Generated by Django 5.1.1 on 2024-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trys', '0003_book_delete_post_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
