# Generated by Django 5.1.1 on 2024-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trys", "0004_book_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
