# Generated by Django 5.1.1 on 2024-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trys", "0016_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.DateField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
    ]
