# Generated by Django 5.1.1 on 2024-10-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trys', '0018_movieapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieapp',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
